// yingif_ffi.h
// C header for Rust FFI functions
// This would be generated by cbindgen from your Rust library

#ifndef YINGIF_FFI_H
#define YINGIF_FFI_H

#include <stdint.h>

// Opaque pointer to Rust processor
typedef struct YinGifProcessor YinGifProcessor;

// Create a new processor instance
YinGifProcessor* yingif_processor_new(void);

// Free a processor instance
void yingif_processor_free(YinGifProcessor* processor);

// Process a BGRA frame
// Returns 0 on success, error code otherwise
int32_t yingif_process_frame(
    YinGifProcessor* processor,
    const uint8_t* bgra_data,
    int32_t width,
    int32_t height,
    int32_t target_size,
    int32_t palette_size,
    uint8_t* out_indices,
    uint32_t* out_palette
);

// Create a GIF89a from cube tensor data
// Returns 0 on success, error code otherwise
int32_t yingif_create_gif89a(
    const uint8_t* indices,
    const uint32_t* palette,
    int32_t cube_size,
    int32_t palette_size,
    int32_t delay_ms,
    uint8_t* out_data,
    int32_t out_capacity,
    int32_t* out_size
);

// Estimate GIF size for buffer allocation
int32_t yingif_estimate_gif_size(
    int32_t cube_size,
    int32_t palette_size
);

#endif // YINGIF_FFI_H