# SwiftLint configuration for RGB2GIF2VOXEL
# Strict baseline for quality and stability

# Paths to include/exclude
included:
  - RGB2GIF2VOXEL

excluded:
  - RGB2GIF2VOXEL/Bridge/Generated
  - RGB2GIF2VOXEL/Bridge/rgb2gif_processor.swift
  - RGB2GIF2VOXEL/Bridge/rgb2gif_processorFFI.h
  - RGB2GIF2VOXEL/Bridge/rgb2gif_processorFFI.modulemap
  - Frameworks
  - ThirdParty
  - build
  - DerivedData

# Rules configuration
disabled_rules:
  - todo # Allow TODO comments during development
  - file_length # Some complex files may be long
  - type_body_length # Some types need to be comprehensive
  - function_body_length # Some processing functions are necessarily complex

opt_in_rules:
  - force_unwrapping # Prevent ! usage
  - force_cast # Prevent as! usage
  - force_try # Prevent try! usage
  - implicitly_unwrapped_optional # Avoid IUOs
  - empty_xctest_method
  - private_outlet
  - yoda_condition
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher

# Rule configurations
force_cast:
  severity: error

force_unwrapping:
  severity: error

force_try:
  severity: error

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  allowed_symbols: "_"
  validates_start_with_lowercase: false

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 3
  function_level: 3

custom_rules:
  no_print_statements:
    name: "Print Statements"
    regex: '^\s*print\('
    message: "Use os_log or Logger instead of print()"
    severity: warning

  avoid_string_interpolation_in_logs:
    name: "String Interpolation in Logs"
    regex: 'os_log\([^)]*\\('
    message: "Avoid string interpolation in os_log, use format specifiers instead"
    severity: warning

analyzer_rules:
  - unused_declaration
  - unused_import