#!/bin/bash

echo "=================="
echo "RGB2GIF2VOXEL"
echo "=================="
echo ""
echo "✅ App has been successfully built and exported!"
echo ""
echo "📱 To install on your iPhone:"
echo ""
echo "Option 1: Using Xcode (Recommended)"
echo "1. Open RGB2GIF2VOXEL.xcodeproj in Xcode"
echo "2. Connect your iPhone via USB"
echo "3. Select your iPhone as the run destination (top toolbar)"
echo "4. Press the Play button (⏵) or Cmd+R"
echo ""
echo "Option 2: Using Apple Configurator 2"
echo "1. Open Apple Configurator 2"
echo "2. Connect your iPhone"
echo "3. Drag the .app file from:"
echo "   build/export/RGB2GIF2VOXEL.ipa"
echo ""
echo "Option 3: Using Xcode command line"
echo "Run this command:"
echo "xcrun devicectl device install app --device [YOUR_DEVICE_ID] build/export/RGB2GIF2VOXEL.ipa"
echo ""
echo "📦 Built app location:"
echo "   IPA: $(pwd)/build/export/RGB2GIF2VOXEL.ipa"
echo "   Archive: $(pwd)/build/RGB2GIF2VOXEL.xcarchive"
echo ""
echo "🎯 Key Features:"
echo "   • 128x128 high-quality GIF capture"
echo "   • 90° rotation fix applied"
echo "   • Optimized STBN 3D dithering"
echo "   • Swift-only streamlined UX"
echo "   • 3D voxel visualization (ready for integration)"
echo ""
echo "Ready to capture amazing GIFs! 📸"