#!/bin/bash
# START_MONITORING.sh - Launch performance monitor for RGB2GIF2VOXEL

echo "================================================"
echo "🚀 RGB2GIF2VOXEL DEPLOYMENT COMPLETE!"
echo "================================================"
echo ""
echo "✅ App built successfully"
echo "✅ App installed on iPhone"
echo ""
echo "⚠️  NEXT STEPS:"
echo ""
echo "1. 🔓 UNLOCK YOUR iPHONE"
echo ""
echo "2. 📱 TAP THE RGB2GIF2VOXEL APP ICON TO LAUNCH"
echo ""
echo "3. 📊 MONITOR PERFORMANCE IN ANOTHER TERMINAL:"
echo "   ./Scripts/monitor_device_logs.sh"
echo ""
echo "================================================"
echo "APP DETAILS:"
echo "  Bundle ID: YIN.RGB2GIF2VOXEL"
echo "  Device ID: 00008150-00113DCA0280401C"
echo "================================================"
echo ""
echo "TESTING CHECKLIST:"
echo "  [ ] App launches without crash"
echo "  [ ] Camera permission requested"
echo "  [ ] Camera preview shows"
echo "  [ ] Debug overlay visible (top-right)"
echo "  [ ] FPS shows ~25-30"
echo "  [ ] Memory < 200MB"
echo "  [ ] Tap capture button to start"
echo "  [ ] Watch frame counter 0/256 → 256/256"
echo "  [ ] Export GIF after capture"
echo ""
echo "================================================"
echo ""
echo "To manually launch the app via command line (after unlocking):"
echo "xcrun devicectl device process launch --device '00008150-00113DCA0280401C' 'YIN.RGB2GIF2VOXEL'"
echo ""
echo "To monitor logs:"
echo "./Scripts/monitor_device_logs.sh"