[package]
name = "binding-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uniffi-bindgen"
path = "generate_bindings.rs"

[dependencies]
uniffi = { version = "0.28", features = ["cli"] }